#/bin/sh


git clone git@github.com:bitedits/5ht.co
git clone git@github.com:bitedits/sokhatsky.art
git clone git@github.com:bitedits/archive.sokhatsky.art
git clone git@github.com:bitedits/c--
git clone git@github.com:bitedits/crazierl
git clone git@github.com:bitedits/tim
git clone git@github.com:bitedits/ling
git clone git@github.com:bitedits/.github
git clone git@github.com:bitedits/rt
git clone git@github.com:bitedits/kianRiscV
git clone git@github.com:bitedits/skynet
git clone git@github.com:bitedits/N64
git clone git@github.com:bitedits/kernel
git clone git@github.com:bitedits/mcu
git clone git@github.com:bitedits/rts
git clone git@github.com:bitedits/be
git clone git@github.com:bitedits/sc
git clone git@github.com:bitedits/computer
git clone git@github.com:bitedits/qgroundcontrol
git clone git@github.com:bitedits/PX4-Autopilot
git clone git@github.com:bitedits/nuttx-apps
git clone git@github.com:bitedits/lvgl
git clone git@github.com:bitedits/snes
git clone git@github.com:bitedits/switch
git clone git@github.com:bitedits/uvgRTP
git clone git@github.com:bitedits/link16
git clone git@github.com:bitedits/gsm
git clone git@github.com:bitedits/sh
git clone git@github.com:bitedits/ps3
git clone git@github.com:bitedits/ps2
git clone git@github.com:bitedits/game
git clone git@github.com:bitedits/retro
git clone git@github.com:bitedits/minimig
git clone git@github.com:bitedits/RG351P
git clone git@github.com:bitedits/atx
git clone git@github.com:bitedits/x299
git clone git@github.com:bitedits/se30
git clone git@github.com:bitedits/M396F
git clone git@github.com:bitedits/a2000
git clone git@github.com:bitedits/a1200
git clone git@github.com:bitedits/msx
git clone git@github.com:bitedits/xt
git clone git@github.com:bitedits/zx
git clone git@github.com:bitedits/genesis
git clone git@github.com:bitedits/ps1
git clone git@github.com:bitedits/vaio
git clone git@github.com:bitedits/pocket
git clone git@github.com:bitedits/miranda
git clone git@github.com:bitedits/tv
git clone git@github.com:bitedits/lk
git clone git@github.com:bitedits/N64Recomp
git clone git@github.com:bitedits/XenonRecomp
git clone git@github.com:bitedits/ps3mfw
git clone git@github.com:bitedits/ps3gim
git clone git@github.com:bitedits/ps3rco
git clone git@github.com:bitedits/ps3keys
git clone git@github.com:bitedits/ps3tools
git clone git@github.com:bitedits/ps2sdk
git clone git@github.com:bitedits/ps3sce
git clone git@github.com:bitedits/ps3xport
git clone git@github.com:bitedits/t2sde
git clone git@github.com:bitedits/rpcs3
git clone git@github.com:bitedits/3dav
git clone git@github.com:bitedits/ps3spe
git clone git@github.com:bitedits/PSn00bSDK
git clone git@github.com:bitedits/SGDK
git clone git@github.com:bitedits/tiny3d
git clone git@github.com:bitedits/libcart
git clone git@github.com:bitedits/N64brew-GameJam2024
git clone git@github.com:bitedits/N64FlashcartMenu
git clone git@github.com:bitedits/SanniCartReader
git clone git@github.com:bitedits/framework64
git clone git@github.com:bitedits/n64sdk
git clone git@github.com:bitedits/dosbox-x
git clone git@github.com:bitedits/RetroArch
git clone git@github.com:bitedits/SummerCart64
git clone git@github.com:bitedits/kirby64
git clone git@github.com:bitedits/TIC-80
git clone git@github.com:bitedits/pl_mpeg
git clone git@github.com:bitedits/ps3sdk
git clone git@github.com:bitedits/hekate
git clone git@github.com:bitedits/Apple-II-R0
git clone git@github.com:bitedits/QMTECH_Cyclone_V_SoC_KFB
git clone git@github.com:bitedits/uemacs
git clone git@github.com:bitedits/spresense-hw-design-files
git clone git@github.com:bitedits/N64-Sausage64
git clone git@github.com:bitedits/sm64
git clone git@github.com:bitedits/rp1-hacking
git clone git@github.com:bitedits/N64-Platform64
git clone git@github.com:bitedits/dasm-mips
git clone git@github.com:bitedits/dasm-pdp11
git clone git@github.com:bitedits/binaries
git clone git@github.com:bitedits/bugz
git clone git@github.com:bitedits/UEFI-Bootloader
git clone git@github.com:bitedits/simple_tdl
git clone git@github.com:bitedits/dasm-arm
git clone git@github.com:bitedits/n64bootloader
git clone git@github.com:bitedits/dasm-intel
git clone git@github.com:bitedits/mini-vmac-setup
git clone git@github.com:bitedits/libreultra
git clone git@github.com:bitedits/TegraRcmGUI
git clone git@github.com:bitedits/AGZ
git clone git@github.com:bitedits/ps3rsx
git clone git@github.com:bitedits/xf86-video-ps3
git clone git@github.com:bitedits/ps3root
git clone git@github.com:bitedits/64dd-schematics
git clone git@github.com:bitedits/aqcc
git clone git@github.com:bitedits/beos
git clone git@github.com:bitedits/N64-Cartrige
git clone git@github.com:bitedits/UltraCIC
git clone git@github.com:bitedits/N64_3DRenderingTest
git clone git@github.com:bitedits/breakout
git clone git@github.com:bitedits/gxe
